### ISSUE TITLE
QR code feature proposal

### ISSUE THREAD

**Issue by AbhinavGor** [thep-vit/tweBackendv1#20]
- Add QR codes for every user so that they can be scanned by admin for attendance purposes during any on campus events.

**Comment by sanjitk7** [comment]
How do you propose we go about it?

**Comment by AbhinavGor** [comment]
There is npm package called qrcode. That should work fine.

**Comment by sanjitk7** [comment]
Work out the details and give me an update sometime soon.

**Comment by sanjitk7** [comment]
Closing this issue for now. Would have better applications after going back to campus.
